### ISSUE TITLE
in old version i can`t stoped(to release the camera) the camera

### ISSUE THREAD

**Issue by Y-E-P** [LivotovLabs/CamView#14]
I can`t stop the camera for free a camera process for other applications.

```
@Override
public void onBackPressed() {
    scanner.stopScanner();
    super.onBackPressed();

}

@Override
protected void onPause() {
    scanner.stopScanner();
    super.onPause();
}

/*@Override
protected void onStop() {
    scanner.stopScanner();
    super.onStop();
}*/

@Override
protected void onResume() {
    scanner.startScanner();
    super.onResume();
}

@Override
protected void onDestroy() {
    scanner.stopScanner();
    scanner = null;
    super.onDestroy();
}
```

**Comment by livotov** [comment]
Sorry, did not get what you mean. You mean that stopScanner() method in 2.0.0.DEV1-SNAPSHOT does not release the camera ? Or something other ?

**Comment by Y-E-P** [comment]
When I press a "Home button" to hide the my application and open other app(wich uses a camera) i take a error(other program can`t use a camera because scanner.stopScanner() is not released a camera).

I use this library compile('eu.livotov.labs:zxscanlib:2.0.1@aar') { transitive = true }

**Comment by Y-E-P** [comment]
But on 2.0.0.DEV1-SNAPSHOT is works fine in my opinion:)

**Comment by livotov** [comment]
Yes, this seems to be a bug in previous version. Also checked 2.0.0 and it releases the camera correctly on stopScanner

**Comment by Y-E-P** [comment]
like this compile('eu.livotov.labs:zxscanlib:2.0.0@aar') { transitive = true }???

**Comment by livotov** [comment]
no, like that:

```
 compile ('eu.livotov.labs:camview:2.0.0.DEV1-SNAPSHOT@aar') {transitive=true}
```

Note, that zxscanlib project is deprecated now. All further development is performed here, in CamView repo.

**Comment by Y-E-P** [comment]
this library is not work correctly,i have this problem https://github.com/LivotovLabs/CamView/issues/7

**Comment by livotov** [comment]
#7 was copied from zxscanlib. It contains the same problem which is not fixed at the moment

**Comment by Y-E-P** [comment]
but on old zxscanlib camera works fine for me...

**Comment by Y-E-P** [comment]
ok,i use old fersion.but how i can release() a camera???

**Comment by livotov** [comment]
basically it should release it - it calls the proper method

```
public void stopScanner()
    {
        shutodownThreadingSubsystem();
        camera.stop();
    }
```

so not sure why it is failing to release. you can checkout the sources and try to debug it

regarding the "but on old zxscanlib camera works fine for me..." - could you please create a new ticket for that and attach the screenshots with the problem ? Probably you're experiencing another issue.
