### ISSUE TITLE
Size of Scanning Area

### ISSUE THREAD

**Issue by mtangoo** [LivotovLabs/CamView#15]
Currently scanning area is very small (red rectangle) and it makes hard to scan and adding time for recise scanning. I tried my a agains [This App](https://play.google.com/store/apps/details?id=tw.mobileapp.qrcode.banner) and mine took time to put QR code right under the scanner.

Is there a way to increase (or at least provide a way) to make something like linked in app?

**Comment by Y-E-P** [comment]
I think you must to set custom HUD setHudImageResource(R.drawable.my_hud_image);
it works for me

**Comment by livotov** [comment]
@mtangoo , actually, red rectangle is just an artwork. Actual scanning area equals to entire image and d decoder reads entire preview from the camera (0,0 width, height), so you don't have to put your barcode right below the red square. Even if you put your barcode to the corner, it should be decoded.

As @Y-E-P mentioned, you may put your own image via the setHudImageResource(...) method, however this will change just a visual appearance.

If it does not scan the QR code when it is not exactly below the red square, let me know, this could be some bug

P.S. don't forget there is also a throttling timeout set for duplicate barcodes, so once barcode is read, same one will not be decoded within some time (5 seconds by default, AFAIK).

**Comment by mtangoo** [comment]
You are right. I had false impression that it somehow works only if you put it in the rectangle.
The real issue is I forgot to add Camera permission to Manifest. I thing it will do good to add it in readme

**Comment by mtangoo** [comment]
@Y-E-P do you have sample Image
