### ISSUE TITLE
NullpointerException for switch flash on/off

### ISSUE THREAD

**Issue by mtangoo** [LivotovLabs/CamView#17]
**UPDATE**

I tried the code below  you provided and it gives nullpointer exception

(Heading was Add ability to switch flash on/off)
It will be nice to be able to switch camera flash on/off.
pseudocode

``` java
scanner.start();
if(scanner.hasFlash())
    scanner.switchOn()

```

**Comment by livotov** [comment]
already there :)

```
scanner.getCamera().getController().switchFlashlight(true|false);
```

**Comment by mtangoo** [comment]
Let me test it ( a Thomas :))

**Comment by mtangoo** [comment]
I get Null pointer exception with this code

``` java
flashBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                scanner.startScanner();
                if(mFlashIsOn)
                {
                    scanner.getCamera().getController().switchFlashlight(false);
                    mFlashIsOn = false;
                }
                else
                {
                    scanner.getCamera().getController().switchFlashlight(true);
                    mFlashIsOn = false;
                }

            }
        });
```

**Comment by livotov** [comment]
startScanner is an async operation - it takes some time to initialize the camera. So you need to check getController() for null

**Comment by livotov** [comment]
P.S. master branch already contains extended ScannerViewEventListener with extra callbacks for listening camera init/shutdown errors. This will appear in the next snapshot too.

**Comment by mtangoo** [comment]
I will wait to see if it works there. So far getController() is always null

**Comment by livotov** [comment]
it can't be always null, you simply trying to access it too early. See the sample app bundled + also you can now try 2.0.0.DEV4-SNAPSHOT

**Comment by mtangoo** [comment]
Thanks.
I waited like 10minutes then I pressed the button to light it. is that too early? ;)
I will test the latest tomorrow. its night here!

**Comment by livotov** [comment]
if you stopped the scanner at that moment - it will be back to null :)

**Comment by mtangoo** [comment]
(y)

**Comment by mtangoo** [comment]
tested 2.0.0.DEV4-SNAPSHOT.
It works perfect!
