### ISSUE TITLE
How To: Make Recognition faster

### ISSUE THREAD

**Issue by mtangoo** [LivotovLabs/CamView#19]
I'm testing My Mobile Scanning against Scanner electronic device [See here](http://www.posunitech.com/products_detail/&productId=84.html) and I can see its very fast compared to the phone scanning. I know it is dedicated for that and wanted to know if there is any way to speed up mobile scanning.

**Comment by livotov** [comment]
I think apps cannot be as fast as hardware scanners, as they do use not only special firmware but also completely different camera and optics.

**Comment by mtangoo** [comment]
Thanks.
