### ISSUE TITLE
Fatal Exception: java.lang.NoSuchFieldError android.os.AsyncTask.THREAD_POOL_EXECUTOR

### ISSUE THREAD

**Issue by pabloff9** [LivotovLabs/CamView#3]
Hi there.
I'm getting this exception on Android 2.3.4. It seems to me that the cause is this line:

outstandingTask.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR);

being called on api level < 11.
I'm no expert, but it seems this answer might help: http://stackoverflow.com/a/18764323/1796236

Thanks for the great software and I hope this helps improving it.

**Comment by livotov** [comment]
fixed in 1.1.0
