### ISSUE TITLE
galaxy s6 camera preview is stretched 

### ISSUE THREAD

**Issue by livotov** [LivotovLabs/CamView#7]
Moved from zxscanview project, reported by @Leaghte  https://github.com/Leaghte

Hi , i tested lib on few devices. Working fine, but on galaxy s6 camera preview is stretched. See the picture below. HUD is not in the middle :(

**Comment by oiramcro** [comment]
please fix this

**Comment by livotov** [comment]
You can try fresh sources from the master or check the maven version 2.0.0.DEV2-SNAPSHOT
It contains quick fix attempt to aspect ratio. please try and let me know how it will work on your device

Thanks

**Comment by mtangoo** [comment]
@oiramcro does it still happen with snapshot4?

**Comment by livotov** [comment]
since snapshot 2 it should be fixed.
