### ISSUE TITLE
Installing on Maven Latest

### ISSUE THREAD

**Issue by mtangoo** [LivotovLabs/CamView#9]
I want to install 2.0.0.DEV1-SNAPSHOT (latest). Putting in version does not work.
Would you update the installation guide (telling us what to put in "version" in gradle, instead of x.y.z) for getting the latest?

I'm sorry that am not Gradle/Maven maverick if this is obvious!
S.

**Comment by livotov** [comment]
Simply replace x.y.z to 2.0.0.DEV1-SNAPSHOT 
and that's all ;)

**Comment by mtangoo** [comment]
it did not work. Did you try it? Grale complains that library is not found
I will try again and see if there is any change.

I use Android studio latest

**Comment by livotov** [comment]
did you include the maven repo url as well ? Because it is not in the maven central but on our own company repo, so you have to add the repo url as described in the readme.

Anyway, updated readme to replace x.y.z to latest version :)

**Comment by mtangoo** [comment]
I was doing it wrong way. Thanks for docs!
